global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'webfrontend'
    static_configs:
      - targets: ['host.docker.internal:5323'] # hard-coded port matches launchSettings.json
  - job_name: 'weatherappapi'
    static_configs:
      - targets: ['host.docker.internal:5264'] # hard-coded port matches launchSettings.json