global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'AspireCloudLab.Web'
    static_configs:
      - targets: ['host.docker.internal:5323'] # hard-coded port matches launchSettings.json